modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "inspectability"
version = "${version}"
displayName = "Inspectability"
authors = "LunazStudios"
description = '''
A mod that allows players to inspect item models in-game, providing a closer and detailed view of the item's appearance.
'''
side = "CLIENT"
logoFile = "icon.png"

[[dependencies.inspectability]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.inspectability]]
modId = "minecraft"
type = "required"
versionRange = "1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.inspectability]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "inspectability.mixins.json"
